set_project("EternalWorld")
set_version("0.1.0-alpha.1")
set_xmakever("3.0.0")
set_allowedplats("windows")
set_allowedarchs("x64")
add_rules("mode.release", "mode.debug")
set_runtimes("MD")
set_languages("c++20")
set_toolchains("clang-cl")

-- One fixed recipe tree: official XMake packages, overridden by official LL recipes.
-- Nested XMake builds cache repositories in an unordered map; use identical sources.
add_repositories("levimc-repo .deps/ci-repositories/eternal", {rootdir = os.scriptdir()})
add_requires("levilamina 26.51.6", {configs = {target_type = "server"}})
add_requires("levibuildscript 0.6.1")
add_requires("symbolprovider v1.3.0")
add_requires("nlohmann_json v3.12.0")
-- Match the SDK tag's actual xmake.lua, rather than its stale recipe dependency.
add_requireconfs("levilamina.parallel-hashmap", {override = true, version = "v2.0.0"})

local modules = {"EternalCore", "EternalCommerce", "EternalLife", "EternalWorld",
                 "EternalContent", "EternalManagement", "EternalPresentation", "EternalEncounters"}
local sqlite = ".deps/sqlite/sqlite-amalgamation-3530400"

local function common()
    add_includedirs("sdk/EternalSDK/include")
    add_defines("NOMINMAX", "UNICODE", "WIN32_LEAN_AND_MEAN", "_HAS_CXX23=1")
    set_exceptions("cxx")
    add_cxflags("/EHa", "/utf-8", "/W4")
    set_symbols("debug")
end

target("EternalSQLite")
    set_kind("static")
    set_default(false)
    set_languages("c11")
    add_files(sqlite .. "/sqlite3.c")
    add_defines("SQLITE_THREADSAFE=1", "SQLITE_DQS=0", "SQLITE_ENABLE_API_ARMOR=1")
    add_includedirs(sqlite, {public = true})
target_end()

target("EternalDomain")
    set_kind("static")
    set_default(false)
    common()
    add_files("modules/EternalCore/domain/Core.cpp", "modules/EternalCore/domain/Sha256.cpp")
    add_includedirs("modules/EternalCore/domain", sqlite)
    add_deps("EternalSQLite")
target_end()

target("CommerceDomain")
    set_kind("static")
    set_default(false)
    common()
    add_files("modules/EternalCommerce/domain/Commerce.cpp", "modules/EternalCommerce/domain/Sha256.cpp")
    add_includedirs("modules/EternalCommerce/domain", sqlite)
    add_deps("EternalSQLite")
target_end()

target("EternalHost")
    set_kind("shared")
    common()
    add_rules("@levibuildscript/linkrule")
    add_packages("levilamina", "symbolprovider", "nlohmann_json")
    add_files("host/EternalHost/HostMod.cpp", "host/EternalHost/runtime/*.cpp")
    if os.isdir("host/EternalHost/native") then
        add_files("host/EternalHost/native/*.cpp")
    end
    add_includedirs("host/EternalHost", "host/EternalHost/runtime", "host/EternalHost/native")
    set_targetdir("bin/Eternal")
target_end()

for _, name in ipairs(modules) do
    target(name)
        set_kind("shared")
        common()
        add_defines("ETERNAL_MODULE_BUILD")
        add_files("modules/" .. name .. "/Module.cpp")
        set_targetdir("bin/Eternal/modules")
        if name == "EternalCore" then
            add_defines("ETERNAL_CORE_BUILD")
            add_files("modules/EternalCore/api/ApiService.cpp")
            add_files("modules/EternalCore/runtime/Runtime.cpp")
            if os.isfile("modules/EternalCore/api/Phase2Service.cpp") then
                add_files("modules/EternalCore/api/Phase2Service.cpp")
            end
            add_includedirs("modules/EternalCore/api", "modules/EternalCore/runtime", "modules/EternalCore/domain", sqlite)
            add_packages("nlohmann_json")
            add_syslinks("bcrypt")
            add_deps("EternalDomain")
        end
        if name == "EternalCommerce" then
            add_includedirs("modules/EternalCommerce/domain", sqlite)
            add_deps("CommerceDomain")
        end
    target_end()
end

target("CoreDomainTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_files("tests/EternalCore/core_tests.cpp")
    add_includedirs("modules/EternalCore/domain", sqlite)
    add_deps("EternalDomain")
    set_targetdir("bin/tests")
target_end()

target("Phase2DomainTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_files("tests/EternalCore/phase2_domain_tests.cpp")
    add_includedirs("modules/EternalCore/domain", sqlite)
    add_deps("EternalDomain")
    set_targetdir("bin/tests")
target_end()

target("CommerceDomainTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_files("tests/EternalCommerce/commerce_tests.cpp")
    add_includedirs("modules/EternalCommerce/domain", sqlite)
    add_deps("CommerceDomain")
    set_targetdir("bin/tests")
target_end()

target("Phase2RuntimeTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_defines("ETERNAL_CORE_RUNTIME_TESTING", "ETERNAL_CORE_VALIDATION_BUILD")
    add_packages("nlohmann_json")
    add_files("tests/EternalCore/phase2_runtime_tests.cpp", "modules/EternalCore/runtime/Runtime.cpp", "modules/EternalCore/api/ApiService.cpp")
    if os.isfile("modules/EternalCore/api/Phase2Service.cpp") then
        add_files("modules/EternalCore/api/Phase2Service.cpp")
    end
    add_includedirs("modules/EternalCore/runtime", "modules/EternalCore/api", "modules/EternalCore/domain", sqlite)
    add_deps("EternalDomain")
    add_syslinks("bcrypt")
    set_targetdir("bin/tests")
target_end()

target("CoreApiTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_files("tests/EternalCore/api_service_test.cpp", "modules/EternalCore/api/ApiService.cpp")
    add_includedirs("modules/EternalCore/api")
    set_targetdir("bin/tests")
target_end()

target("HostRuntimeTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/EternalHost/runtime_tests.cpp", "host/EternalHost/runtime/*.cpp")
    add_includedirs("host/EternalHost/runtime")
    set_targetdir("bin/tests")
target_end()

target("EternalExampleContracts")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_defines("ETERNAL_MODULE_BUILD")
    add_packages("nlohmann_json")
    add_files("templates/EternalModule/Module.cpp", "templates/EternalModule/tests/ModuleContract.cpp")
    set_targetdir("bin/tests")
target_end()

target("Phase2NativeBridgeTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/Host/phase2_native_bridge_tests.cpp", "host/EternalHost/runtime/*.cpp")
    add_includedirs("host/EternalHost/runtime")
    set_targetdir("bin/tests")
target_end()

target("ModuleArtifactTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/Host/real_module_tests.cpp", "host/EternalHost/runtime/*.cpp")
    add_includedirs("host/EternalHost/runtime")
    set_targetdir("bin/tests")
target_end()

target("ConfigTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/Host/config_tests.cpp", "host/EternalHost/runtime/Config.cpp")
    add_includedirs("host/EternalHost/runtime")
    set_targetdir("bin/tests")
target_end()

target("SDKCppTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_defines("ETERNAL_MODULE_BUILD")
    add_files("sdk/EternalSDK/tests/cpp_headers.cpp")
    set_targetdir("bin/tests")
target_end()

target("Phase2ClientContracts")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_files("sdk/EternalSDK/tests/phase2_client_contract.cpp")
    set_targetdir("bin/tests")
target_end()

target("CoreValidationModule")
    set_kind("shared")
    set_default(false)
    common()
    add_defines("ETERNAL_MODULE_BUILD")
    add_files("tests/Fixtures/CoreValidationModule.cpp")
    set_targetdir("bin/validation")
target_end()

target("ValidationModuleTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/Host/validation_module_tests.cpp", "host/EternalHost/runtime/*.cpp")
    add_includedirs("host/EternalHost/runtime")
    add_deps("CoreValidationModule")
    set_targetdir("bin/tests")
target_end()

-- Validation-only binaries never enter bin/Eternal or the release allowlist.
target("EternalCoreValidation")
    set_kind("shared")
    set_default(false)
    common()
    add_defines("ETERNAL_MODULE_BUILD", "ETERNAL_CORE_BUILD", "ETERNAL_CORE_VALIDATION_BUILD")
    add_files("modules/EternalCore/Module.cpp", "modules/EternalCore/api/ApiService.cpp", "modules/EternalCore/runtime/Runtime.cpp")
    add_includedirs("modules/EternalCore/api", "modules/EternalCore/runtime", "modules/EternalCore/domain", sqlite)
    add_packages("nlohmann_json")
    add_deps("EternalDomain")
    add_syslinks("bcrypt")
    set_targetdir("bin/validation")
target_end()

target("EternalTestConsumer")
    set_kind("shared")
    set_default(false)
    common()
    add_defines("ETERNAL_MODULE_BUILD")
    add_files("tests/Fixtures/EternalTestConsumer.cpp")
    add_includedirs(sqlite)
    add_deps("EternalSQLite")
    set_targetdir("bin/validation")
target_end()

target("SyntheticMultiUserTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_defines("ETERNAL_CORE_RUNTIME_TESTING", "ETERNAL_CORE_VALIDATION_BUILD")
    add_packages("nlohmann_json")
    add_files("tests/EternalCore/synthetic_multi_user_tests.cpp", "modules/EternalCore/runtime/Runtime.cpp", "modules/EternalCore/api/ApiService.cpp")
    add_includedirs("modules/EternalCore/runtime", "modules/EternalCore/api", "modules/EternalCore/domain", sqlite)
    add_deps("EternalDomain")
    add_syslinks("bcrypt")
    set_targetdir("bin/tests")
target_end()

target("ConsumerModuleTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/Host/consumer_module_tests.cpp", "host/EternalHost/runtime/*.cpp")
    add_includedirs("host/EternalHost/runtime", sqlite)
    add_deps("EternalSQLite", "EternalCoreValidation", "EternalTestConsumer")
    set_targetdir("bin/tests")
target_end()

target("EternalCommerceValidation")
    set_kind("shared")
    set_default(false)
    common()
    add_defines("ETERNAL_MODULE_BUILD", "ETERNAL_COMMERCE_VALIDATION_BUILD")
    add_files("modules/EternalCommerce/Module.cpp")
    add_includedirs("modules/EternalCommerce/domain", sqlite)
    add_deps("CommerceDomain")
    set_targetdir("bin/validation")
target_end()

target("CommerceModuleTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/Host/commerce_module_tests.cpp", "host/EternalHost/runtime/*.cpp")
    add_includedirs("host/EternalHost/runtime", sqlite)
    add_deps("EternalSQLite", "EternalCoreValidation", "EternalCommerceValidation")
    set_targetdir("bin/tests")
target_end()

target("ProductionRuntimeIsolationTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_packages("nlohmann_json")
    add_files("tests/EternalCore/production_runtime_tests.cpp", "modules/EternalCore/runtime/Runtime.cpp", "modules/EternalCore/api/ApiService.cpp")
    add_includedirs("modules/EternalCore/runtime", "modules/EternalCore/api", "modules/EternalCore/domain", sqlite)
    add_deps("EternalDomain")
    add_syslinks("bcrypt")
    set_targetdir("bin/tests")
target_end()

target("ProductionIsolationTests")
    set_kind("binary")
    set_default(false)
    common()
    add_undefines("NDEBUG")
    add_files("tests/Host/production_isolation_tests.cpp")
    set_targetdir("bin/tests")
target_end()
