#include "../../modules/EternalCore/runtime/Runtime.hpp"
#include "../../modules/EternalCore/domain/Core.hpp"
#include <EternalSDK/Core/Phase2Client.hpp>
#include <nlohmann/json.hpp>
#include <Windows.h>
#include <array>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <stdexcept>
#include <thread>
#ifndef ETERNAL_CORE_RUNTIME_TESTING
#error Phase2RuntimeTests requires its private test-only compilation macro
#endif

using eternal::core::runtime::Runtime;
using Json=nlohmann::json;
namespace fs=std::filesystem;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class T> T dto(){T value{};value.struct_size=sizeof(T);value.struct_version=1;return value;}
bool same(EcId128 a,EcId128 b){return a.high==b.high&&a.low==b.low;}
struct Reply{EcStatus status;EcNativeReply reply;std::string text;};
struct Fixture {
    static inline unsigned serial{};
    fs::path root=fs::temp_directory_path()/("EternalRuntimeSynthetic_"+std::to_string(GetCurrentProcessId())+"_"+std::to_string(++serial));
    std::unique_ptr<Runtime> runtime;
    std::uint64_t clock=1000,requestSerial=1;
    EmHostContext host=dto<EmHostContext>();
    EcNativePlayerIdentity owner{},alice{},bob{};
    EcNativeJoinResult ownerJoin{},aliceJoin{},bobJoin{};
    bool publishFailure{};unsigned published{};
    std::vector<EcPhase2OutboxNotice> notices;
    Fixture(bool config=true,bool development=true,bool autoStart=true){
        fs::create_directories(root/"config");
        if(config)writeConfig(development);
        host.abi_major=EM_ABI_MAJOR;host.abi_minor=EM_ABI_MINOR;host.instance=this;host.capabilities=EM_HOST_SERVICES|EM_HOST_EVENTS;
        host.publish_service=[](void*,const EmServiceOffer*)noexcept->EmStatus{return EM_OK;};
        host.publish_event=[](void* context,const EmEvent* event)noexcept->EmStatus{
            auto& f=*static_cast<Fixture*>(context);++f.published;
            if(!event||event->data_size!=sizeof(EcPhase2OutboxNotice))return EM_ABI_MISMATCH;
            f.notices.push_back(*static_cast<const EcPhase2OutboxNotice*>(event->data));return f.publishFailure?EM_INTERNAL_ERROR:EM_OK;
        };
        runtime=std::make_unique<Runtime>(root/"config",root/"data",[this]{return clock;});
        owner=identity(0xaa,1000,"Owner");alice=identity(0xbb,1001,"Alice");bob=identity(0xcc,1002,"Bob");
        if(autoStart){require(runtime->load(),"Runtime load");require(runtime->enable(host)==EM_OK,"Runtime enable");if(config)joinAll();}
    }
    ~Fixture(){runtime.reset();fs::remove_all(root);}
    void writeConfig(bool development){
        const auto caps=Json::array({EC_MODULE_CAP_PLAYER_READ_NAME,EC_MODULE_CAP_PERMISSION_CHECK_NAME,EC_MODULE_CAP_MONEY_NAME,EC_MODULE_CAP_REPUTATION_NAME,EC_MODULE_CAP_AUDIT_NAME,EC_MODULE_CAP_EVENTS_NAME});
        std::ofstream(root/"config"/"core.json")<<Json{{"ownerXuid","1000"},{"developmentValidation",development},{"validatedAssets",false},{"moduleCapabilities",{{"core",caps},{"test",caps},{"reader",Json::array({EC_MODULE_CAP_PLAYER_READ_NAME})}}}}.dump();
    }
    static EcNativePlayerIdentity identity(uint8_t byte,uint64_t xuid,const char* name){auto value=dto<EcNativePlayerIdentity>();for(auto& b:value.trusted_uuid.bytes)b=byte;value.client_uuid=value.trusted_uuid;value.trusted_xuid=xuid;value.display_name={name,static_cast<uint32_t>(std::strlen(name)),0};value.is_fully_authenticated=1;return value;}
    const EcNativeIngressApi* api()const{return runtime->nativeApi();}
    EcRequestId requestId(){return {requestSerial++,777};}
    EcNativeJoinResult join(const EcNativePlayerIdentity& identity){auto out=dto<EcNativeJoinResult>();require(api()->authenticated_player(api()->bridge_nonce,&identity,&out)==EC_OK,"Player authentication");return out;}
    void joinAll(){ownerJoin=join(owner);aliceJoin=join(alice);bobJoin=join(bob);}
    EcNativeCommandRequest commandRequest(const std::string& text,const EcNativePlayerIdentity* player,EcRequestId request={}){
        auto value=dto<EcNativeCommandRequest>();value.request_id=request.high||request.low?request:requestId();value.origin=player?EC_NATIVE_ORIGIN_PLAYER:EC_NATIVE_ORIGIN_SERVER_CONSOLE;if(player)value.player=*player;value.command_text={text.data(),static_cast<uint32_t>(text.size()),0};return value;
    }
    Reply send(const std::string& text,const EcNativePlayerIdentity* player,EcRequestId id={}){auto request=commandRequest(text,player,id);std::array<char,16384> storage{};EcUtf8Buffer output{storage.data(),static_cast<uint32_t>(storage.size()),0};auto reply=dto<EcNativeReply>();auto code=api()->native_command(api()->bridge_nonce,&request,&reply,&output);return {code,reply,storage.data()};}
    Reply send(const std::string& text){return send(text,&owner);}
    Reply complete(EcNativePendingAction token,const EcNativePlayerIdentity& player,int button=0,EcRequestId id={}){auto request=dto<EcNativeActionCompletionRequest>();request.request_id=id.high||id.low?id:requestId();request.player=player;request.pending_action=token;request.selected_button=button;std::array<char,16384> storage{};EcUtf8Buffer output{storage.data(),static_cast<uint32_t>(storage.size()),0};auto reply=dto<EcNativeReply>();auto code=api()->complete_action(api()->bridge_nonce,&request,&reply,&output);return {code,reply,storage.data()};}
    int64_t balance(const EcNativePlayerIdentity& player,const char* which="money"){auto answer=send(std::string("balance self ")+which,&player);require(answer.status==EC_OK,"Balance diagnostic");return Json::parse(answer.text).at("minorUnits").get<int64_t>();}
    EcNativeModuleBindingResult bind(std::string module="core",uint64_t generation=1,int64_t limit=1000000,int64_t budget=6000000,uint64_t caps=EC_MODULE_CAP_ALL){auto request=dto<EcNativeModuleBindingRequest>();request.module_id={module.data(),static_cast<uint32_t>(module.size()),0};request.module_generation=generation;request.approved_module_capabilities=caps;request.approved_permissions=EC_P2_PERMISSION_ALL;request.money_limit_per_request=limit;request.reputation_limit_per_request=10000;request.money_budget_per_period=budget;request.reputation_budget_per_period=60000;request.budget_period_ms=60000;auto out=dto<EcNativeModuleBindingResult>();require(api()->bind_module(api()->bridge_nonce,&request,&out)==EC_OK,"Module bind");return out;}
    void publicFeatures(){require(runtime->testEnableFeatures(EC_P2_FEATURE_ALL)==EC_OK,"Synthetic features");}
    EcPhase2MutationRequest mutation(EcCallerContext caller,EcPlayerId target,const EcNativePlayerIdentity& actor,uint32_t op=EC_P2_OP_ASSET_ADD,int64_t amount=100,EcId128 key={13,14},uint32_t which=EC_P2_ASSET_MONEY,EcPlayerId recipient={},uint64_t role=0){
        EcPhase2MutationRequest request{};request.meta.struct_size=sizeof(request);request.meta.struct_version=1;request.meta.caller_context=caller;request.meta.request_id=requestId();request.meta.idempotency_key=key;request.target=target;request.recipient=recipient;request.operation=op;request.asset=which;request.minor_units=amount;request.role_mask=role;request.reason={"synthetic test",14,0};require(runtime->testIssueCapability(actor,request,request.meta.capability)==EC_OK,"Core synthetic scoped issuance");return request;
    }
    EcPhase2Receipt poll(const EcNativeModuleBindingResult& binding,const EcNativePlayerIdentity& actor,EcPlayerId player,EcReceiptId receipt,EcStatus expected=EC_OK){auto scope=mutation(binding.caller_context,player,actor,EC_P2_OP_RECEIPT_READ,0,{100,101},0);EcPhase2ReceiptRequest request{};request.meta=scope.meta;request.meta.struct_size=sizeof(request);request.receipt_id=receipt;auto out=dto<EcPhase2Receipt>();require(binding.scoped_api->poll_receipt_v2(&request,&out)==expected,"Public receipt result");return out;}
};
struct RouteHarness {
    Fixture& fixture;
    EcNativeModuleBindingResult binding;
    eternal::sdk::Phase2Client client;
    EcPhase2Invocation last{};
    EcPhase2InvocationGrant grant{};
    std::function<EcStatus(RouteHarness&)> action;
    std::string failure;
    unsigned calls{};
    explicit RouteHarness(Fixture& f,std::uint64_t operations=EC_P2_PERMISSION_ALL):fixture(f),binding(f.bind("test")){
        auto host=f.host;host.instance=this;host.query_service=[](void* instance,const EmServiceRequest* request,EmServiceReference* out)noexcept->EmStatus{
            auto& h=*static_cast<RouteHarness*>(instance);if(!request->required_capabilities)return EM_INVALID_ARGUMENT;
            *out=dto<EmServiceReference>();out->table=h.binding.scoped_api;out->table_size=h.binding.table_size;out->api_major=1;out->api_minor=EC_PHASE2_API_MINOR;return EM_OK;
        };
        require(eternal::sdk::Phase2Client::discover(host,EC_MODULE_CAP_ALL,client)==EM_OK,"Route SDK scoped discover");
        auto route=dto<EcPhase2CommandRouteRequest>();route.route_id={"check",5,0};route.operation_mask=operations;route.callback=callback;route.user=this;
        require(client.registerRoute(route)==EC_OK,"Route register while production flags zero");
    }
    static EcStatus EC_CALL callback(void* user,const EcPhase2Invocation* invocation,EcUtf8Buffer* reply)noexcept{
        auto& h=*static_cast<RouteHarness*>(user);try{
            require(invocation&&invocation->struct_size==sizeof(*invocation)&&invocation->struct_version==1,"Callback DTO");
            h.last=*invocation;h.last.arguments={};++h.calls;auto code=h.action?h.action(h):EC_OK;
            constexpr char response[]="{\"fixture\":true}";reply->required=sizeof(response);if(reply->capacity<sizeof(response))return EC_BUFFER_TOO_SMALL;
            std::memcpy(reply->data,response,sizeof(response));return code;
        }catch(const std::exception& error){h.failure=error.what();return EC_INTERNAL_ERROR;}catch(...){h.failure="Unknown callback exception";return EC_INTERNAL_ERROR;}
    }
    EcStatus authorize(std::uint32_t operation,std::uint32_t asset=EC_P2_ASSET_NONE,std::int64_t amount=0,EcPlayerId target={}){
        auto request=dto<EcPhase2InvocationAuthorization>();request.invocation=last.invocation;request.target=target.high||target.low?target:last.subject;
        request.operation=operation;request.asset=asset;request.minor_units=amount;return client.authorize(request,grant);
    }
    EcPhase2MutationRequest mutation(std::int64_t amount=100){EcPhase2MutationRequest request{};request.meta.capability=grant.capability;request.meta.request_id=last.request_id;request.meta.idempotency_key={111,222};request.target=last.subject;request.operation=EC_P2_OP_ASSET_ADD;request.asset=EC_P2_ASSET_MONEY;request.minor_units=amount;request.reason={"sdk-route-test",14,0};return request;}
    EcStatus unregister(){auto request=dto<EcPhase2RouteRemovalRequest>();request.route_id={"check",5,0};return client.unregisterRoute(request);}
    Reply invoke(const EcNativePlayerIdentity* actor=nullptr,EcRequestId request={}){auto reply=fixture.send("invoke test check arguments",actor?actor:&fixture.owner,request);if(!failure.empty())throw std::runtime_error(failure);return reply;}
};
template<class F> void test(const char* name,F run,unsigned& groups){run();++groups;std::cout<<"PASS "<<name<<'\n';}
}

int main(){try{unsigned groups=0;
    test("health-only boot and console isolation",[]{Fixture f(false);require(Json::parse(f.send("status",nullptr).text).at("healthOnly")==true,"Health-only");auto output=dto<EcNativeJoinResult>();require(f.api()->authenticated_player(f.api()->bridge_nonce,&f.owner,&output)==EC_UNSUPPORTED,"No identity bootstrap without config");require(f.send("asset self money 100 key reason",nullptr).status==EC_UNSUPPORTED,"No console assets");},groups);
    test("configuration fails closed",[]{Fixture f(true,true,false);std::ofstream(f.root/"config"/"core.json")<<"{\"ownerXuid\":\"1000\",\"validatedAssets\":true}";require(!f.runtime->load(),"Production switch refuses unvalidated enable");Fixture duplicate(true,true,false);std::ofstream(duplicate.root/"config"/"core.json")<<"{\"ownerXuid\":\"1000\",\"ownerXuid\":\"1001\"}";require(!duplicate.runtime->load(),"Duplicate config field");},groups);
    test("strict trusted identity and spoofed bridge",[]{Fixture f;auto out=dto<EcNativeJoinResult>();require(f.api()->authenticated_player({1,2},&f.owner,&out)==EC_DENIED,"Bridge nonce spoof");auto bad=f.alice;bad.is_fully_authenticated=0;require(f.api()->authenticated_player(f.api()->bridge_nonce,&bad,&out)==EC_DENIED,"Unauthenticated");bad=f.alice;bad.is_simulated=1;require(f.api()->authenticated_player(f.api()->bridge_nonce,&bad,&out)==EC_DENIED,"Simulated");bad=f.alice;bad.client_uuid=f.bob.client_uuid;require(f.api()->authenticated_player(f.api()->bridge_nonce,&bad,&out)==EC_DENIED,"UUID mismatch");require(f.send("identity self",&f.alice).status==EC_OK,"Registered player");},groups);
    test("public production and legacy gates remain closed",[]{Fixture f;auto info=dto<EcPhase2FeatureInfo>();require(f.runtime->phase2Api()->get_phase2_features(&info)==EC_OK&&!info.enabled&&info.development_only,"Production closed");auto old=dto<EcFeatureInfo>();require(f.runtime->phase2Api()->v1_0.get_features(&old)==EC_OK&&!old.enabled,"Legacy closed");auto binding=f.bind();auto request=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner);auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&request,&out)==EC_UNSUPPORTED,"Core private test token has no development authority");},groups);
    test("module policy default deny and cap intersection",[]{Fixture f;auto request=dto<EcNativeModuleBindingRequest>();const char name[]="unknown";request.module_id={name,7,0};request.module_generation=1;request.approved_module_capabilities=EC_MODULE_CAP_ALL;request.approved_permissions=EC_P2_PERMISSION_ALL;request.budget_period_ms=60000;auto out=dto<EcNativeModuleBindingResult>();require(f.api()->bind_module(f.api()->bridge_nonce,&request,&out)==EC_DENIED,"Host declaration not private approval");auto reader=f.bind("reader",1,1000000,6000000);f.publicFeatures();auto write=f.mutation(reader.caller_context,f.ownerJoin.player_id,f.owner);auto receipt=dto<EcPhase2Submission>();require(reader.scoped_api->submit_mutation(&write,&receipt)==EC_DENIED,"Private reader policy strips money");},groups);
    test("native adjustment balances and persistent replay",[]{Fixture f;auto first=f.send("asset Alice money 500 credit reason");require(first.status==EC_OK&&f.balance(f.alice)==500,"Credit");auto second=f.send("asset Alice money 500 credit reason");require(second.status==EC_OK&&second.text==first.text&&f.balance(f.alice)==500,"Persistent idempotency");require(f.send("asset Alice money 600 credit reason").status==EC_CONFLICT,"Changed canonical payload");require(f.send("receipt credit").text==first.text,"Receipt key lookup");},groups);
    test("console never impersonates Owner and Player lacks MoneyAdjust",[]{Fixture f;require(f.send("asset Alice money 100 noauth reason",nullptr).status==EC_DENIED,"Console rejected");require(f.send("asset self money 100 playerkey reason",&f.alice).status==EC_DENIED,"Player role restriction");require(f.balance(f.alice)==0,"No wallet effect");require(Json::parse(f.send("receipt playerkey",&f.alice).text).at("status")=="rejected","Durable denial");},groups);
    test("buffer-size retry neither mutates twice nor remints form",[]{Fixture f;const std::string command="asset Alice money 100 sized reason";auto request=f.commandRequest(command,&f.owner);auto reply=dto<EcNativeReply>();EcUtf8Buffer output{};require(f.api()->native_command(f.api()->bridge_nonce,&request,&reply,&output)==EC_BUFFER_TOO_SMALL,"Sizing");std::vector<char> bytes(output.required);output={bytes.data(),static_cast<uint32_t>(bytes.size()),0};require(f.api()->native_command(f.api()->bridge_nonce,&request,&reply,&output)==EC_OK&&f.balance(f.alice)==100,"Single mutation retry");auto formId=f.requestId();auto a=f.send("authority-test",&f.owner,formId);auto b=f.send("authority-test",&f.owner,formId);require(a.status==EC_OK&&same(a.reply.pending_action,b.reply.pending_action)&&a.text==b.text,"Stable form token");require(f.send("status",&f.owner,formId).status==EC_CONFLICT,"Request ID fingerprint");},groups);
    test("old UI role withdrawal has durable denial",[]{Fixture f;require(f.send("role Alice EconomyManager on give-role reason").status==EC_OK,"Role grant");auto opened=f.send("authority-test",&f.alice);require(opened.status==EC_OK,"Authorized form opened");require(f.send("role Alice EconomyManager off revoke-role reason").status==EC_OK,"Role revoked");auto closed=f.complete(opened.reply.pending_action,f.alice);require(closed.status==EC_REVOKED&&Json::parse(closed.text).at("status")=="rejected","Old UI denied receipt");require(f.balance(f.alice)==0,"Old UI no money");},groups);
    test("expired pending action records a durable receipt",[]{Fixture f;auto opened=f.send("authority-test");f.clock+=60001;auto closed=f.complete(opened.reply.pending_action,f.owner);require(closed.status==EC_EXPIRED&&Json::parse(closed.text).at("status")=="rejected","Expired receipt");require(f.balance(f.owner)==0,"Expiry no assets");},groups);
    test("zero account revision is still a form precondition",[]{Fixture f;auto opened=f.send("authority-test");require(opened.status==EC_OK,"Initial revision zero form");require(f.send("asset self money 200 changed-zero reason").status==EC_OK,"Account changed");auto closed=f.complete(opened.reply.pending_action,f.owner);require(closed.status==EC_CONFLICT&&Json::parse(closed.text).at("status")=="rejected","Zero revision precondition");require(f.balance(f.owner)==200,"Old UI no second grant");},groups);
    test("form subject mismatch cancellation and consumed token",[]{Fixture f;auto opened=f.send("authority-test");require(f.complete(opened.reply.pending_action,f.alice).status==EC_DENIED,"Wrong subject");require(f.complete(opened.reply.pending_action,f.owner,-1).status==EC_OK,"Cancellation");require(f.complete(opened.reply.pending_action,f.owner).status==EC_REVOKED&&f.balance(f.owner)==0,"Consumed action");},groups);
    test("cache quotas preserve Owner and pending completion",[]{Fixture f;require(f.send("role Alice EconomyManager on setup reason").status==EC_OK,"Setup");auto pending=f.send("authority-test",&f.alice);require(pending.status==EC_OK,"Open before pressure");unsigned blocked=0;for(unsigned i=0;i<280;++i)if(f.send("status",&f.alice).status==EC_LIMIT_EXCEEDED)++blocked;require(blocked>250,"Per player cache quota");require(f.send("status").status==EC_OK&&f.send("status",nullptr).status==EC_OK,"Reserved owner console capacity");require(f.complete(pending.reply.pending_action,f.alice).status==EC_OK,"Form completion separate capacity");},groups);
    test("cached reply rechecks session and role revision",[]{Fixture f;auto id=f.requestId();require(f.send("roles self",&f.alice,id).status==EC_OK,"First read");require(f.send("role Alice Builder on changed reason").status==EC_OK,"Revision changed");require(f.send("roles self",&f.alice,id).status==EC_REVOKED,"Stale cached authority rejected");},groups);
    test("joining new connection invalidates old capability and disconnect",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto request=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner);auto original=f.ownerJoin;auto current=f.join(f.owner);require(current.session_generation>original.session_generation,"Join generation increases");auto disconnect=dto<EcNativeDisconnectRequest>();disconnect.client_uuid=f.owner.client_uuid;disconnect.expected_session_generation=original.session_generation;require(f.api()->disconnect(f.api()->bridge_nonce,&disconnect)==EC_CONFLICT,"Late old disconnect rejected");auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&request,&out)==EC_REVOKED,"Old session capability");require(f.send("identity self").status==EC_OK,"Current session remains online");},groups);
    test("public request scope caller token expiry and amount",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto request=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner);auto out=dto<EcPhase2Submission>();auto bad=request;bad.meta.capability={44,55};require(binding.scoped_api->submit_mutation(&bad,&out)==EC_DENIED,"Forged token");bad=request;bad.meta.caller_context={99,88};require(binding.scoped_api->submit_mutation(&bad,&out)==EC_DENIED,"Forged caller");bad=request;bad.target=f.aliceJoin.player_id;require(binding.scoped_api->submit_mutation(&bad,&out)==EC_DENIED,"Target scope");bad=request;bad.minor_units+=1;require(binding.scoped_api->submit_mutation(&bad,&out)==EC_DENIED,"Amount scope");bad=request;bad.meta.struct_size=sizeof(bad.meta);require(binding.scoped_api->submit_mutation(&bad,&out)==EC_ABI_MISMATCH,"Full DTO size");f.clock+=60001;require(binding.scoped_api->submit_mutation(&request,&out)==EC_EXPIRED,"Steady expiry");require(f.balance(f.owner)==0,"No rejected side effects");},groups);
    test("public budgets and durable rejected retry",[]{Fixture f;auto binding=f.bind("core",1,200,300);f.publicFeatures();auto a=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_ASSET_ADD,200,{1,1});auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&a,&out)==EC_OK,"Within budget");auto b=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_ASSET_ADD,200,{2,2});require(binding.scoped_api->submit_mutation(&b,&out)==EC_BUDGET_EXCEEDED,"Period budget");auto denial=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(denial.state==EC_RECEIPT_REJECTED&&denial.target_balance==200,"Rejected receipt snapshot");require(f.balance(f.owner)==200,"Budget denial atomic");},groups);
    test("accurate committed money reputation role and transfer receipts",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto out=dto<EcPhase2Submission>();auto credit=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_ASSET_ADD,1000,{1,10});require(binding.scoped_api->submit_mutation(&credit,&out)==EC_OK,"Credit");auto oldReceipt=out.receipt_id;auto receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(receipt.asset==EC_P2_ASSET_MONEY&&receipt.operation==EC_P2_OP_ASSET_ADD&&receipt.target_balance==1000&&receipt.target_revision&&receipt.completed_at_unix_ms&&receipt.audit_revision&&receipt.ledger_revision,"Credit receipt exact DTO");auto transfer=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_TRANSFER,300,{2,10},EC_P2_ASSET_MONEY,f.aliceJoin.player_id);require(binding.scoped_api->submit_mutation(&transfer,&out)==EC_OK,"Transfer");receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(same(receipt.target,f.ownerJoin.player_id)&&same(receipt.recipient,f.aliceJoin.player_id)&&receipt.target_balance==700&&receipt.recipient_balance==300&&receipt.target_revision&&receipt.recipient_revision,"Transfer snapshots");auto old=f.poll(binding,f.owner,f.ownerJoin.player_id,oldReceipt);require(old.target_balance==1000,"Historical receipt never reads current balance");auto rep=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ASSET_ADD,30,{3,10},EC_P2_ASSET_REPUTATION);require(binding.scoped_api->submit_mutation(&rep,&out)==EC_OK,"Reputation");receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(receipt.asset==EC_P2_ASSET_REPUTATION&&receipt.target_balance==30,"Reputation units");auto change=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ROLE_GRANT,0,{4,10},0,{},EC_P2_ROLE_BUILDER);require(binding.scoped_api->submit_mutation(&change,&out)==EC_OK,"Role");receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(receipt.asset==EC_P2_ASSET_NONE&&receipt.role_mask==EC_P2_ROLE_BUILDER&&receipt.operation==EC_P2_OP_ROLE_GRANT&&receipt.target_revision,"Role receipt revision");},groups);
    test("deduct revoke and readonly Player receipt DTOs",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto out=dto<EcPhase2Submission>();auto credit=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_ASSET_ADD,500,{111,112});require(binding.scoped_api->submit_mutation(&credit,&out)==EC_OK,"Fund");auto debit=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_ASSET_DEDUCT,200,{113,114});require(binding.scoped_api->submit_mutation(&debit,&out)==EC_OK,"Deduct");auto receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(receipt.operation==EC_P2_OP_ASSET_DEDUCT&&receipt.minor_units==200&&receipt.target_balance==300&&receipt.target_revision==2,"Debit precise operation snapshot");auto grant=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ROLE_GRANT,0,{115,116},0,{},EC_P2_ROLE_BUILDER);require(binding.scoped_api->submit_mutation(&grant,&out)==EC_OK,"Grant");auto revoke=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ROLE_REVOKE,0,{117,118},0,{},EC_P2_ROLE_BUILDER);require(binding.scoped_api->submit_mutation(&revoke,&out)==EC_OK,"Revoke");receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(receipt.operation==EC_P2_OP_ROLE_REVOKE&&receipt.role_mask==EC_P2_ROLE_BUILDER&&receipt.target_revision==f.aliceJoin.role_revision+2,"Role revoke snapshot");auto player=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ROLE_GRANT,0,{119,120},0,{},EC_P2_ROLE_PLAYER);require(binding.scoped_api->submit_mutation(&player,&out)==EC_DENIED,"Player readonly");receipt=f.poll(binding,f.owner,f.ownerJoin.player_id,out.receipt_id);require(receipt.role_mask==EC_P2_ROLE_PLAYER&&receipt.state==EC_RECEIPT_REJECTED&&receipt.target_revision==f.aliceJoin.role_revision+2,"Readonly rejected snapshot");},groups);
    test("RoleSnapshot information and expected revision stay scoped",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto scoped=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.alice,EC_P2_OP_ROLE_READ,0,{121,122},0);EcPhase2QueryRequest query{};query.meta=scoped.meta;query.meta.struct_size=sizeof(query);query.target=f.aliceJoin.player_id;auto role=dto<EcPhase2RoleSnapshot>();require(binding.scoped_api->read_roles(&query,&role)==EC_OK&&(role.role_mask&EC_P2_ROLE_PLAYER)&&role.permission_mask,"Readonly role and permission info");auto bit=UINT64_C(1)<<(EC_P2_OP_ASSET_ADD-1);require(!(role.permission_mask&bit),"Player snapshot has no money adjustment");auto write=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner);write.meta.expected_revision=99;auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&write,&out)==EC_DENIED,"Caller cannot alter signed revision");require(f.balance(f.owner)==0,"No altered-precondition effect");},groups);
    test("Player owns only its own transfer receipt",[]{Fixture f;require(f.send("asset Alice money 400 fund reason").status==EC_OK,"Fund Alice");auto binding=f.bind();f.publicFeatures();auto transfer=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.alice,EC_P2_OP_TRANSFER,100,{50,60},EC_P2_ASSET_MONEY,f.bobJoin.player_id);auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&transfer,&out)==EC_OK,"Ordinary transfer");require(f.poll(binding,f.alice,f.aliceJoin.player_id,out.receipt_id).target_balance==300,"Player self receipt");f.poll(binding,f.bob,f.bobJoin.player_id,out.receipt_id,EC_NOT_FOUND);},groups);
    test("immutable Owner Player and module revocation",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto out=dto<EcPhase2Submission>();auto change=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ROLE_GRANT,0,{41,42},0,{},EC_P2_ROLE_OWNER);require(binding.scoped_api->submit_mutation(&change,&out)==EC_DENIED&&out.receipt_id.low,"Owner immutable audited");auto request=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner);auto revoke=dto<EcNativeModuleRevokeRequest>();revoke.caller_context=binding.caller_context;revoke.caller_generation=binding.caller_generation;revoke.reason={"test revoke",11,0};require(f.api()->revoke_module(f.api()->bridge_nonce,&revoke)==EC_OK,"Revoke module");require(binding.scoped_api->submit_mutation(&request,&out)==EC_DENIED,"Revoked module context");},groups);
    test("unknown target has durable rejection without identity creation",[]{Fixture f;auto initial=Json::parse(f.runtime->diagnostics()).at("players");auto rejected=f.send("asset Nobody money 100 missing-key reason");require(rejected.status==EC_NOT_FOUND&&Json::parse(rejected.text).at("status")=="rejected","Missing target receipt");require(f.send("receipt missing-key").text==rejected.text,"Missing target durable receipt");require(Json::parse(f.runtime->diagnostics()).at("players")==initial,"No invented player");},groups);
    test("ordinary Player outbox is self-scoped and uses current versions",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto out=dto<EcPhase2Submission>();auto credit=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ASSET_ADD,500,{80,81});require(binding.scoped_api->submit_mutation(&credit,&out)==EC_OK,"Credit event");auto oldRequest=credit.meta.request_id;auto transfer=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.alice,EC_P2_OP_TRANSFER,100,{82,83},EC_P2_ASSET_MONEY,f.bobJoin.player_id);require(binding.scoped_api->submit_mutation(&transfer,&out)==EC_OK,"Transfer events");auto scope=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.alice,EC_P2_OP_OUTBOX_READ,0,{84,85},0);EcPhase2OutboxRequest request{};request.meta=scope.meta;request.meta.struct_size=sizeof(request);request.limit=100;std::array<EcPhase2OutboxEvent,100> rows{};auto buffer=dto<EcPhase2OutboxBuffer>();buffer.data=rows.data();buffer.capacity=100;require(binding.scoped_api->read_outbox(&request,&buffer)==EC_OK&&buffer.count==2,"Only Alice rows");for(unsigned i=0;i<buffer.count;++i)require(same(rows[i].target,f.aliceJoin.player_id)&&rows[i].authoritative_balance==400&&rows[i].account_revision&&rows[i].occurred_at_unix_ms,"Current-authority event snapshot");require(same(rows[0].request_id,oldRequest),"Durable originating request ID");},groups);
    test("role outbox has no monetary asset and caller-owned buffers",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto role=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.owner,EC_P2_OP_ROLE_GRANT,0,{90,91},0,{},EC_P2_ROLE_BUILDER);auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&role,&out)==EC_OK,"Role event");auto scope=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner,EC_P2_OP_OUTBOX_READ,0,{92,93},0);EcPhase2OutboxRequest query{};query.meta=scope.meta;query.meta.struct_size=sizeof(query);query.limit=100;auto buffer=dto<EcPhase2OutboxBuffer>();require(binding.scoped_api->read_outbox(&query,&buffer)==EC_BUFFER_TOO_SMALL&&buffer.required==1,"Outbox sizing");EcPhase2OutboxEvent row{};buffer.data=&row;buffer.capacity=1;require(binding.scoped_api->read_outbox(&query,&buffer)==EC_OK&&row.type==EC_P2_OUTBOX_ROLE_CHANGED&&row.asset==EC_P2_ASSET_NONE&&row.authoritative_balance==0&&row.account_revision&&row.occurred_at_unix_ms,"Role event DTO");},groups);
    test("outbox failure retries without treating publish as ack",[]{Fixture f;require(f.send("asset Alice money 100 outbox-failed reason").status==EC_OK,"Create outbox");f.publishFailure=true;require(f.api()->tick(f.api()->bridge_nonce,UINT64_MAX)==EC_OK&&f.published==1,"Failed publication recorded");for(unsigned i=0;i<100;++i)require(f.api()->tick(f.api()->bridge_nonce,0)==EC_OK,"Tick throttled");require(f.published==1,"No repeated tick publications");f.publishFailure=false;std::this_thread::sleep_for(std::chrono::milliseconds(1100));f.clock+=1100;require(f.api()->tick(f.api()->bridge_nonce,0)==EC_OK&&f.published==2,"Persistent retry succeeds");require(f.notices.back().event_cursor==f.notices.front().event_cursor,"Same durable event retried");f.runtime->disable();eternal::core::Core reader((f.root/"data"/"core.sqlite3").string(),"1000");require(reader.selfcheck().value.pendingDeliveries>0,"Publish success is not delivery acknowledgement");},groups);
    test("permission subject mismatch and strict invalid DTOs",[]{Fixture f;auto binding=f.bind();f.publicFeatures();auto scope=f.mutation(binding.caller_context,f.aliceJoin.player_id,f.alice,EC_P2_OP_PERMISSION_CHECK,0,{94,95},EC_P2_ASSET_MONEY);EcPhase2PermissionRequest request{};request.meta=scope.meta;request.meta.struct_size=sizeof(request);request.subject=f.bobJoin.player_id;request.target=f.aliceJoin.player_id;request.operation=EC_P2_OP_ASSET_ADD;request.asset=EC_P2_ASSET_MONEY;auto decision=dto<EcPhase2PermissionDecision>();require(binding.scoped_api->check_permission(&request,&decision)==EC_DENIED,"Subject cannot be substituted");auto invalid=f.mutation(binding.caller_context,f.ownerJoin.player_id,f.owner);invalid.reason.length=UINT32_MAX;auto out=dto<EcPhase2Submission>();require(binding.scoped_api->submit_mutation(&invalid,&out)==EC_INVALID_ARGUMENT,"Oversized view rejected before reading");require(f.send("asset Alice money 100 bad-control reason\nnext").status==EC_INVALID_UTF8,"Control rejected");auto output=dto<EcNativeJoinResult>();require(f.api()->authenticated_player(f.api()->bridge_nonce,nullptr,&output)==EC_DENIED,"Null identity");},groups);
    test("restart retains identity balances and receipts",[]{Fixture f;auto first=f.send("asset Alice money 200 restart-key reason");require(first.status==EC_OK,"Initial credit");auto originalId=f.aliceJoin.player_id;f.runtime.reset();f.runtime=std::make_unique<Runtime>(f.root/"config",f.root/"data",[&]{return f.clock;});require(f.runtime->load()&&f.runtime->enable(f.host)==EM_OK,"Restart");f.joinAll();require(same(originalId,f.aliceJoin.player_id)&&f.balance(f.alice)==200,"Stable identity state");require(f.send("receipt restart-key").text==first.text,"Durable receipt after restart");require(f.send("asset Alice money 200 restart-key reason").status==EC_OK&&f.balance(f.alice)==200,"Retry after restart no double credit");},groups);
    test("game-thread gate while owner remains alive",[]{Fixture f;auto binding=f.bind();auto revoke=dto<EcNativeModuleRevokeRequest>();revoke.caller_context=binding.caller_context;revoke.caller_generation=binding.caller_generation;revoke.reason={"offthread revoke",16,0};EcStatus offthread=EC_OK,offthreadRevoke=EC_OK;std::thread worker([&]{offthread=f.api()->tick(f.api()->bridge_nonce,0);offthreadRevoke=f.api()->revoke_module(f.api()->bridge_nonce,&revoke);});worker.join();require(offthread==EC_WRONG_THREAD&&offthreadRevoke==EC_WRONG_THREAD,"Live owner has no terminal exception");},groups);
    test("terminal revoke requires OS proof of exited owner thread",[]{Fixture f(true,true,false);require(f.runtime->load(),"Terminal fixture load");EcNativeModuleBindingResult binding{};std::thread server([&]{require(f.runtime->enable(f.host)==EM_OK,"Server thread enable");f.joinAll();binding=f.bind();});server.join();auto request=dto<EcNativeModuleRevokeRequest>();request.caller_context=binding.caller_context;request.caller_generation=binding.caller_generation;request.reason={"terminal stop",13,0};require(f.api()->revoke_module(f.api()->bridge_nonce,&request)==EC_OK,"OS proof allows terminal revoke");require(f.api()->tick(f.api()->bridge_nonce,0)==EC_WRONG_THREAD,"Terminal proof never grants asset/event commands");require(f.runtime->disable()==EM_OK,"Terminal memory cleanup");},groups);
    test("public native route closes development capability receipt chain",[]{Fixture f;RouteHarness h(f);h.action=[](RouteHarness& route){
        require(route.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100)==EC_OK,"Public Core-issued grant");
        require((route.grant.flags&EC_P2_CAPABILITY_DEVELOPMENT_ONLY)&&same(route.grant.subject,route.last.subject),"Actual dev scoped subject");
        auto request=route.mutation();EcPhase2Submission submitted{};
        require(route.client.submit(request,submitted)==EC_UNSUPPORTED,"Default SDK production-only");route.client.setDevelopmentValidation(true);
        require(route.client.submit(request,submitted)==EC_OK&&submitted.state==EC_RECEIPT_COMMITTED,"Authorized public development mutation");auto receiptId=submitted.receipt_id;
        require(route.authorize(EC_P2_OP_RECEIPT_READ)==EC_OK,"Receipt grant");EcPhase2ReceiptRequest query{};query.meta.capability=route.grant.capability;query.receipt_id=receiptId;EcPhase2Receipt receipt{};
        require(route.client.receipt(query,receipt)==EC_OK&&receipt.target_balance==100&&receipt.minor_units==100&&same(receipt.request_id,route.last.request_id),"Persistent receipt via public SDK");
        require(route.authorize(EC_P2_OP_OUTBOX_READ)==EC_OK,"Outbox grant");EcPhase2OutboxRequest history{};history.meta.capability=route.grant.capability;history.limit=100;std::array<EcPhase2OutboxEvent,100> rows{};EcPhase2OutboxBuffer output{};output.data=rows.data();output.capacity=rows.size();require(route.client.outbox(history,output)==EC_OK&&output.count==1&&rows[0].authoritative_balance==100,"Public outbox from actual domain");
        return EC_OK;
    };require(h.invoke().status==EC_OK&&f.balance(f.owner)==100,"Native route full chain");auto info=dto<EcPhase2FeatureInfo>();require(f.runtime->phase2Api()->get_phase2_features(&info)==EC_OK&&!info.enabled,"Production flags stay zero");},groups);
    test("invocations reject unknown module route and console",[]{Fixture f;RouteHarness h(f);require(f.send("invoke missing check args").status==EC_NOT_FOUND,"Unknown module");require(f.send("invoke test missing args").status==EC_NOT_FOUND,"Missing route");require(f.send("invoke test check args",nullptr).status==EC_DENIED&&h.calls==0,"Console cannot create player invocation");auto request=dto<EcPhase2InvocationAuthorization>();request.caller_context=h.binding.caller_context;request.invocation={44,55};request.target=f.ownerJoin.player_id;request.operation=EC_P2_OP_IDENTITY_READ;auto out=dto<EcPhase2InvocationGrant>();require(h.binding.scoped_api->authorize_invocation(&request,&out)==EC_REVOKED,"Forged invocation");request.struct_size=sizeof(request)-8;require(h.binding.scoped_api->authorize_invocation(&request,&out)==EC_INVALID_ARGUMENT,"Malformed route authorization ABI");const std::array<uint32_t,2> shortHeader{8,1};require(h.binding.scoped_api->authorize_invocation(reinterpret_cast<const EcPhase2InvocationAuthorization*>(shortHeader.data()),&out)==EC_INVALID_ARGUMENT,"Header-only request has no audit field access");},groups);
    test("invocation is bound to exact module and ends with callback",[]{Fixture f;RouteHarness h(f);auto other=f.bind("core");h.action=[&](RouteHarness& route){auto request=dto<EcPhase2InvocationAuthorization>();request.caller_context=other.caller_context;request.invocation=route.last.invocation;request.target=route.last.subject;request.operation=EC_P2_OP_IDENTITY_READ;auto grant=dto<EcPhase2InvocationGrant>();require(other.scoped_api->authorize_invocation(&request,&grant)==EC_DENIED,"Different module cannot consume token");return route.authorize(EC_P2_OP_IDENTITY_READ);};require(h.invoke().status==EC_OK,"Callback authorized");require(h.authorize(EC_P2_OP_IDENTITY_READ)==EC_REVOKED,"Invocation invalid immediately after callback");},groups);
    test("issued delayed capability survives callback but cannot change scope",[]{Fixture f;RouteHarness h(f);h.action=[](RouteHarness& route){return route.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);};require(h.invoke().status==EC_OK,"Issue deferred action");h.client.setDevelopmentValidation(true);auto request=h.mutation();EcPhase2Submission out{};auto wrong=request;wrong.minor_units=200;require(h.client.submit(wrong,out)==EC_DENIED,"Cannot enlarge signed amount");wrong=request;wrong.target=f.aliceJoin.player_id;wrong.meta.idempotency_key={555,666};require(h.client.submit(wrong,out)==EC_DENIED,"Cannot change target");request.meta.idempotency_key={777,888};require(h.client.submit(request,out)==EC_OK&&f.balance(f.owner)==100,"Delayed signed action valid");},groups);
    test("Player route self read does not grant administrator assets",[]{Fixture f;RouteHarness h(f);h.client.setDevelopmentValidation(true);h.action=[](RouteHarness& route){require(route.authorize(EC_P2_OP_IDENTITY_READ)==EC_OK,"Player self identity");EcPhase2QueryRequest query{};query.meta.capability=route.grant.capability;query.target=route.last.subject;EcPhase2IdentitySnapshot out{};std::array<char,129> name{};EcUtf8Buffer display{name.data(),name.size(),0};require(route.client.identity(query,out,display)==EC_OK&&same(out.player_id,route.last.subject),"Self identity actual domain");return route.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);};require(h.invoke(&f.alice).status==EC_DENIED&&f.balance(f.alice)==0,"Player mutation denied despite dev config");},groups);
    test("route operation mask private policy and budget restrict grants",[]{Fixture f;RouteHarness h(f,UINT64_C(1)<<(EC_P2_OP_IDENTITY_READ-1));h.action=[](RouteHarness& route){return route.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);};require(h.invoke().status==EC_DENIED,"Route cannot request undeclared operation");require(h.unregister()==EC_OK,"Replace route after callback");auto route=dto<EcPhase2CommandRouteRequest>();route.caller_context=h.binding.caller_context;route.route_id={"check",5,0};route.operation_mask=EC_P2_PERMISSION_ALL;route.callback=RouteHarness::callback;route.user=&h;require(h.client.registerRoute(route)==EC_OK,"New declared route");h.action=[](RouteHarness& r){return r.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,1000001);};require(h.invoke().status==EC_BUDGET_EXCEEDED,"Core per-request maximum");auto reader=f.bind("reader");route.caller_context=reader.caller_context;require(reader.scoped_api->register_command_route(&route)==EC_DENIED,"Private module cap intersection");},groups);
    test("callback expiry role revoke disconnect reject active invocation",[]{Fixture f;RouteHarness h(f);h.action=[](RouteHarness& r){r.fixture.clock+=60001;return r.authorize(EC_P2_OP_IDENTITY_READ);};require(h.invoke().status==EC_EXPIRED,"Steady clock expiry while active");require(f.send("role Alice EconomyManager on routegrant reason").status==EC_OK,"Grant role");h.action=[](RouteHarness& r){require(r.fixture.send("role Alice EconomyManager off routedeny reason").status==EC_OK,"Revoke during callback");return r.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);};require(h.invoke(&f.alice).status==EC_REVOKED,"Role revision invalidates invitation");h.action=[](RouteHarness& r){auto request=dto<EcNativeDisconnectRequest>();request.client_uuid=r.fixture.owner.client_uuid;request.expected_session_generation=r.fixture.ownerJoin.session_generation;require(r.fixture.api()->disconnect(r.fixture.api()->bridge_nonce,&request)==EC_OK,"Disconnect during callback");return r.authorize(EC_P2_OP_IDENTITY_READ);};require(h.invoke().status==EC_REVOKED,"Disconnected subject invocation");},groups);
    test("module revoke clears routes capabilities and generation",[]{Fixture f;RouteHarness h(f);h.action=[](RouteHarness& r){return r.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);};require(h.invoke().status==EC_OK,"Issued before revoke");h.client.setDevelopmentValidation(true);auto request=h.mutation();auto revoke=dto<EcNativeModuleRevokeRequest>();revoke.caller_context=h.binding.caller_context;revoke.caller_generation=h.binding.caller_generation;revoke.reason={"module disabled",15,0};require(f.api()->revoke_module(f.api()->bridge_nonce,&revoke)==EC_OK,"Revoke module");EcPhase2Submission out{};require(h.client.submit(request,out)==EC_DENIED,"Revoked signed capability");require(h.invoke().status==EC_NOT_FOUND,"Route removed with module");},groups);
    test("active callback preserves module user and Core lifecycle",[]{Fixture f;RouteHarness h(f);h.action=[](RouteHarness& r){require(r.unregister()==EC_CONFLICT,"Active route cannot release user");require(r.fixture.runtime->disable()==EM_CONFLICT,"Core refuses active callback cleanup");auto revoke=dto<EcNativeModuleRevokeRequest>();revoke.caller_context=r.binding.caller_context;revoke.caller_generation=r.binding.caller_generation;revoke.reason={"reentrant revoke",16,0};require(r.fixture.api()->revoke_module(r.fixture.api()->bridge_nonce,&revoke)==EC_CONFLICT,"No module cleanup while callback borrows state");return r.authorize(EC_P2_OP_IDENTITY_READ);};require(h.invoke().status==EC_OK,"Callback remains valid");require(h.unregister()==EC_OK&&h.invoke().status==EC_NOT_FOUND,"Safe unregister after return");},groups);
    test("native invoke buffer retry executes callback once",[]{Fixture f;RouteHarness h(f);h.client.setDevelopmentValidation(true);h.action=[](RouteHarness& r){auto code=r.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);if(code!=EC_OK)return code;EcPhase2Submission out{};return r.client.submit(r.mutation(),out);};const std::string command="invoke test check args";auto request=f.commandRequest(command,&f.owner);auto reply=dto<EcNativeReply>();EcUtf8Buffer output{};require(f.api()->native_command(f.api()->bridge_nonce,&request,&reply,&output)==EC_BUFFER_TOO_SMALL,"Caller sizing probe");std::vector<char> storage(output.required);output={storage.data(),static_cast<uint32_t>(storage.size()),0};require(f.api()->native_command(f.api()->bridge_nonce,&request,&reply,&output)==EC_OK&&h.calls==1&&f.balance(f.owner)==100,"Cache prevents callback/commit replay");require(f.send("invoke test check changed",&f.owner,request.request_id).status==EC_CONFLICT&&h.calls==1,"Arguments part of fingerprint");},groups);
    test("private development switch is essential even with valid route token",[]{Fixture f(true,false);RouteHarness h(f);h.client.setDevelopmentValidation(true);h.action=[](RouteHarness& r){require(r.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100)==EC_OK,"Scoped grant still authorizes shape");require(!(r.grant.flags&EC_P2_CAPABILITY_DEVELOPMENT_ONLY),"Private switch does not issue dev authority");EcPhase2Submission out{};return r.client.submit(r.mutation(),out);};require(h.invoke().status==EC_UNSUPPORTED&&f.balance(f.owner)==0,"No production or private development availability");},groups);
    test("revoked delayed public action has persistent denied receipt",[]{Fixture f;require(f.send("role Alice EconomyManager on route-ui-grant reason").status==EC_OK,"Grant for delayed action");RouteHarness h(f);h.client.setDevelopmentValidation(true);h.action=[](RouteHarness& r){return r.authorize(EC_P2_OP_ASSET_ADD,EC_P2_ASSET_MONEY,100);};require(h.invoke(&f.alice).status==EC_OK,"Receive real public delayed grant");auto action=h.mutation();require(f.send("role Alice EconomyManager off route-ui-revoke reason").status==EC_OK,"Role changed after invocation");EcPhase2Submission denied{};require(h.client.submit(action,denied)==EC_REVOKED&&denied.state==EC_RECEIPT_REJECTED&&(denied.receipt_id.high||denied.receipt_id.low),"Public stale UI durable denial");h.action=[&](RouteHarness& r){require(r.authorize(EC_P2_OP_RECEIPT_READ)==EC_OK,"Player self receipt capability");EcPhase2ReceiptRequest request{};request.meta.capability=r.grant.capability;request.receipt_id=denied.receipt_id;EcPhase2Receipt receipt{};require(r.client.receipt(request,receipt)==EC_OK&&receipt.state==EC_RECEIPT_REJECTED&&receipt.target_balance==0,"Denied receipt available after role withdrawal");return EC_OK;};require(h.invoke(&f.alice).status==EC_OK&&f.balance(f.alice)==0,"No delayed money effects");},groups);
    std::cout<<"Synthetic Core Runtime: "<<groups<<" groups passed; production DLL features remain zero, no BDS/player validation performed.\n";return 0;
}catch(const std::exception& error){std::cerr<<"FAIL "<<error.what()<<'\n';return 1;}}
