
ALTER TABLE players ADD COLUMN playerId TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN displayName TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN firstSeen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN lastSeen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN identityVersion INTEGER NOT NULL DEFAULT 1 CHECK(identityVersion>0);
ALTER TABLE players ADD COLUMN permissionRevision INTEGER NOT NULL DEFAULT 1 CHECK(permissionRevision>0);
UPDATE players SET playerId='player_'||replace(uuid,'-',''),firstSeen=CAST(strftime('%s','now') AS INTEGER)*1000,lastSeen=CAST(strftime('%s','now') AS INTEGER)*1000;
CREATE UNIQUE INDEX player_id_unique ON players(playerId);
ALTER TABLE accounts ADD COLUMN revision INTEGER NOT NULL DEFAULT 0 CHECK(revision>=0);
UPDATE accounts SET revision=(SELECT count(*) FROM entries WHERE entries.uuid=accounts.uuid AND entries.asset=accounts.asset);
CREATE TABLE roles_v2(uuid TEXT NOT NULL REFERENCES players(uuid),role TEXT NOT NULL CHECK(role IN ('build','economy','law','content','resources','operations','admin','content_manager','economy_manager','builder','moderator')),PRIMARY KEY(uuid,role)) STRICT;
INSERT INTO roles_v2 SELECT uuid,role FROM roles;
DROP TABLE roles;
ALTER TABLE roles_v2 RENAME TO roles;
CREATE TABLE transactions_v2(transactionId TEXT PRIMARY KEY,executorScope TEXT NOT NULL CHECK(executorScope='core.domain.v1' OR (executorScope LIKE 'core.module.%' AND length(executorScope)=76)),idempotencyKey TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('committed','rejected')),createdAt INTEGER NOT NULL,updatedAt INTEGER NOT NULL,payload TEXT NOT NULL,requestHash TEXT NOT NULL,operation TEXT NOT NULL,actorUuid TEXT NOT NULL REFERENCES players(uuid),retryCount INTEGER NOT NULL DEFAULT 0 CHECK(retryCount>=0),resultCode INTEGER NOT NULL DEFAULT 0,moduleId TEXT NOT NULL DEFAULT 'core',requestId TEXT NOT NULL DEFAULT '',permissionRevision INTEGER NOT NULL DEFAULT 0 CHECK(permissionRevision>=0),UNIQUE(executorScope,actorUuid,idempotencyKey)) STRICT;
INSERT INTO transactions_v2(transactionId,executorScope,idempotencyKey,status,createdAt,updatedAt,payload,requestHash,operation,actorUuid,retryCount) SELECT transactionId,executorScope,idempotencyKey,status,createdAt,updatedAt,payload,requestHash,operation,actorUuid,retryCount FROM transactions;
DROP TABLE transactions;
ALTER TABLE transactions_v2 RENAME TO transactions;
CREATE TABLE audit_v2(id INTEGER PRIMARY KEY,transactionId TEXT REFERENCES transactions(transactionId),actorUuid TEXT REFERENCES players(uuid),operation TEXT NOT NULL,reason TEXT NOT NULL,requestHash TEXT NOT NULL,createdAt INTEGER NOT NULL,moduleId TEXT NOT NULL DEFAULT 'core',targetUuid TEXT NOT NULL DEFAULT '',resultCode INTEGER NOT NULL DEFAULT 0,requestId TEXT NOT NULL DEFAULT '',permissionRevision INTEGER NOT NULL DEFAULT 0 CHECK(permissionRevision>=0)) STRICT;
INSERT INTO audit_v2(id,transactionId,actorUuid,operation,reason,requestHash,createdAt) SELECT id,transactionId,actorUuid,operation,reason,requestHash,createdAt FROM audit;
DROP TABLE audit;
ALTER TABLE audit_v2 RENAME TO audit;
CREATE TABLE denial_audit_budget(actorKey TEXT NOT NULL,moduleId TEXT NOT NULL,operation TEXT NOT NULL,day INTEGER NOT NULL,totalCount INTEGER NOT NULL CHECK(totalCount>0),detailedCount INTEGER NOT NULL CHECK(detailedCount>=0 AND detailedCount<=64),PRIMARY KEY(actorKey,moduleId,operation,day)) STRICT;
CREATE TABLE outbox_consumers(consumerId TEXT PRIMARY KEY,createdAt INTEGER NOT NULL) STRICT;
CREATE TABLE outbox_delivery(consumerId TEXT NOT NULL REFERENCES outbox_consumers(consumerId),eventId INTEGER NOT NULL REFERENCES outbox(id),status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','retry','offline','acknowledged')),retryCount INTEGER NOT NULL DEFAULT 0 CHECK(retryCount>=0),nextAttemptAt INTEGER NOT NULL DEFAULT 0,lastError TEXT NOT NULL DEFAULT '',acknowledgedAt INTEGER,PRIMARY KEY(consumerId,eventId)) STRICT;
CREATE INDEX outbox_delivery_pending ON outbox_delivery(consumerId,status,nextAttemptAt,eventId);
PRAGMA user_version=2;
